{{- if not .Values.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: db-user-pass
type: Opaque
data:
  username: {{ .Values.db.username }}
  password: {{ .Values.db.password }}
{{- end }}