{{- if .Values.stateful.enabled }}

---
# Headless service to make pods in the stateful set addressable.

apiVersion: v1
kind: Service
metadata:
  name: headless-svc
  labels:
    app: db
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: db

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-sts
  labels:
    app: app
spec:
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: "Parallel"
  serviceName: headless-svc
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      terminationGracePeriodSeconds: 10
      containers:  
      - name: app
        {{- include "env.db_creds" . | indent 8 }}
        image: {{ .Values.image }}
        ports:
        - containerPort: {{ .Values.containerPort }}
          name: container-port
        resources:
          requests:
            memory: {{ .Values.memoryRequest }}
            cpu: {{ .Values.cpuRequest }}
          limits:
            memory: {{ .Values.memoryLimit }}
            cpu: {{ .Values.cpuLimit }}
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: db-pvc
          mountPath: /app/db
      volumes:
      - name: config-volume
        configMap:
          name: app-cm

  volumeClaimTemplates:
  - metadata:
      name: db-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.stateful.storageRequest }}

{{- end }}
