pipeline {
    agent {
      docker {
        image 'python:3'
        label 'docker'
      }
    }
    stages {
        stage('Test') {
            steps {
              sh """
              python --version
              pip --version
              """
            }
        }
    }
}