# https://github.com/grafana/loki/blob/main/production/docker-compose.yaml
---
version: "3"

networks:
  loki:

services:
  app:
    image: sh3b0/app_python # Or app_nodejs
    # ports:
    #   - "8080:8080"
    networks:
      - loki
  
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./config:/mnt/config
    command: --config.file=/mnt/config/prometheus-config.yaml
    networks:
      - loki

  loki:
    image: grafana/loki:2.5.0
    # ports:
    #   - "3100:3100"
    volumes:
      - ./config:/mnt/config
    command: -config.file=/mnt/config/loki-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.5.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers  # Needed for container logs
      - ./config:/mnt/config
    command: -config.file=/mnt/config/promtail-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
