pipeline {
    agent any
    environment {
        DOCKERHUB_CREDS=credentials('dockerhub')
        PORT=3000
    }
    stages {
        stage('Test') {
            steps {
                nodejs('node-16.14.0') {
                    sh '''
                    cd app_nodejs
                    npm ci
                    npm run ci
                    '''
                }
            }
        }
        stage('Build') {
            steps {
                sh '''
                cd app_nodejs
                docker build -t sh3b0/app_nodejs .
                '''
            }
        }
        stage('Release') {
            steps {
                sh '''
                docker tag sh3b0/app_nodejs sh3b0/app_nodejs:$(git rev-parse --short HEAD)
                echo $DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin
                docker push sh3b0/app_nodejs --all-tags
                '''
            }
        }
    }
}
