pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                dir('app_nodejs') {
                    checkout scm
                }
                nodejs('node-16.14.0') {
                    sh 'npm ci'
                }
            }
        }
    }
}
