---
- name: get running containers
  docker_host_info:
    containers: true
  register: docker_info

- name: stop running containers
  docker_container:
    name: "{{ item }}"
    state: stopped
  loop: "{{ docker_info.containers | map(attribute='Id') | list }}"

- name: "deploy {{ app_name }} app"
  docker_container:
    name: "{{ app_name }}"
    image: "{{ dockerhub_id }}/{{ app_name }}"
    ports:
      - "8080:8080"
