---
- name: "Install and configure nginx on loadbalancer node"
  hosts: loadbalancer
  become: yes
  
  tasks:

  - name: install nginx
    apt:
      name:
        - nginx
      update_cache: yes

  - name: copy nginx config to guest
    ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: restart nginx for config to take effect
    shell: "systemctl restart nginx"
