- name: "Pull and run latest {{ app_name }} image from DockerHub"
  hosts: app
  tasks:
    - name: Stop and remove all previously running containers
      shell: "docker kill $(docker ps -q) || true \
            && docker rm $(docker ps -a -q) || true \
            && docker rmi $(docker images -q) || true"

    - name: "deploy {{ app_name }} app"
      docker_container:
        name: "{{ app_name }}"
        image: "sh3b0/{{ app_name }}"
        ports:
          - "8080:8080"