# Reference: https://github.com/xcad2k/boilerplates/blob/main/ansible/provisoning/ubuntu/install-docker.yaml
---
- name: "Install docker and docker Python SDK on all app nodes"
  hosts: app
  
  become: yes
  tasks:

  # Install Docker
  # --
  - name: install prerequisites
    apt:
      name:
        - apt-transport-https
        - ca-certificates 
        - curl 
        - gnupg-agent
        - software-properties-common
      update_cache: yes

  - name: add apt-key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: add docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable

  - name: install docker 
    apt:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
      update_cache: yes

  - name: add user permissions
    shell: "usermod -aG docker {{ ansible_env.SUDO_USER }}"

  - name: Reset ssh connection to allow user changes to affect 'current login user'
    meta: "reset_connection"

  # Install Docker SDK
  # --
  - name: install python package manager
    apt:
      name: python3-pip
  
  - name: install python sdk
    become_user: "{{ ansible_env.SUDO_USER }}"
    pip:
      name:
        - docker
