# Reference: https://github.com/xcad2k/boilerplates/blob/main/ansible/provisoning/ubuntu/install-docker.yaml
---
- name: "install docker and docker Python SDK on all app nodes"
  hosts: app
  become: true

  tasks:
  - name: install prerequisites
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      update_cache: true

  - name: add apt-key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: add docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable

  - name: install docker
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      update_cache: true

  - name: add user permissions
    user:
      name: "{{ ansible_env.SUDO_USER }}"
      append: true
      groups: docker
    notify:
      reset SSH connection

  - name: install python package manager
    apt:
      name: python3-pip

  - name: install docker sdk for python
    become_user: "{{ ansible_env.SUDO_USER }}"
    pip:
      name:
        - docker

  handlers:
    - name: reset SSH connection
      meta: "reset_connection"