name: CI/CD (Python)

on:
  push:
    branches:
      - main
    paths:
      - "app_python/**"
      
defaults:
  run:
    working-directory: app_python

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt && python -m pytest

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: "sh3b0/app_python:$(git log -1 --pretty=format:%h)"
