name: CI/CD (Python)

on:
  push:
    branches:
      - main
    paths:
      - "app_python/**"
      
defaults:
  run:
    working-directory: app_python

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: |
          pip install -r requirements.txt
          python -m pytest

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
            username: sh3b0
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "TAGNAME=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: sh3b0/app_python:${TAGNAME} , sh3b0/app_python:latest
          cache-from: type=registry,ref=sh3b0/app_python:latest
          cache-to: type=inline
