name: CI (Python)

on:
  push:
    branches:
      - main
    paths:
      - "app_python/**"
      - ".github/workflows/app_python.yaml"
      
defaults:
  run:
    working-directory: app_python

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: |
          pip install pylint pytest
          pip install -r requirements.txt
          pylint app_python
          python -m pytest

  build-and-push:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
            username: sh3b0
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: vars
        run: echo "::set-output name=tagname::$(git rev-parse --short HEAD)"
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: app_python/
          file: app_python/Dockerfile
          push: true
          tags: sh3b0/app_python:${{ steps.vars.outputs.tagname }} , sh3b0/app_python:latest
          cache-from: type=registry,ref=sh3b0/app_python:latest
          cache-to: type=inline
  
  scan:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v3
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: sh3b0/app_python
